let cellMapping = new Map();
cellMapping.set("A", 0);
cellMapping.set("B", 1);
cellMapping.set("C", 2);
cellMapping.set("D", 3);
cellMapping.set("E", 4);
cellMapping.set("F", 5);
cellMapping.set("G", 6);
cellMapping.set("H", 7);
cellMapping.set("I", 8);
cellMapping.set("J", 9);
cellMapping.set("K", 10);
cellMapping.set("L", 11);
cellMapping.set("M", 12);
cellMapping.set("N", 13);
cellMapping.set("O", 14);
cellMapping.set("P", 15);
cellMapping.set("Q", 16);
cellMapping.set("R", 17);
cellMapping.set("S", 18);
cellMapping.set("T", 19);
cellMapping.set("U", 20);
cellMapping.set("V", 21);
cellMapping.set("W", 22);
cellMapping.set("X", 23);
cellMapping.set("Y", 24);
cellMapping.set("Z", 25);
cellMapping.set("AA", 26);
cellMapping.set("AB", 27);
cellMapping.set("AC", 28);
cellMapping.set("AD", 29);
cellMapping.set("AE", 30);
cellMapping.set("AF", 31);
cellMapping.set("AG", 32);

module.exports = cellMapping;